# Generated by Django 5.0.6 on 2024-05-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=32)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store name', max_length=32)),
                ('location', models.CharField(help_text='location store', max_length=64)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name', max_length=32)),
                ('code', models.CharField(help_text='Unit Code', max_length=4)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=32)),
                ('note', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocked.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=32)),
                ('code', models.CharField(help_text='Product code', max_length=8)),
                ('barcode', models.CharField(help_text='Product barcode', max_length=16)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('note', models.TextField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stocked.category')),
                ('purchase_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parchase_unit', to='Stocked.unit')),
                ('sale_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_unit', to='Stocked.unit')),
            ],
        ),
    ]
