# Generated by Django 5.0.6 on 2024-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stocked', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pro_images/default.png', upload_to='pro_images/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
